Fix docker-compose.yml `environment` type
My docker-compose complains that this wasn't the right type:

```
$ docker-compose build
...
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.alice.environment contains {"APPOPTICS_SERVICE_KEY": ""}, which is an invalid type, it should be a string
services.bob.environment contains {"APPOPTICS_SERVICE_KEY": ""}, which is an invalid type, it should be a string
services.caroljs.environment contains {"APPOPTICS_SERVICE_KEY": ""}, which is an invalid type, it should be a string
services.davepy.environment contains {"APPOPTICS_SERVICE_KEY": ""}, which is an invalid type, it should be a string
services.otto.environment contains {"APPOPTICS_SERVICE_KEY": ""}, which is an invalid type, it should be a string
```